/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TeamsIndexRouteImport } from './routes/teams/index'
import { Route as AppsIndexRouteImport } from './routes/apps/index'
import { Route as ApisIndexRouteImport } from './routes/apis/index'
import { Route as TeamsTeamIdRouteImport } from './routes/teams/$teamId'
import { Route as AppsAppIdRouteImport } from './routes/apps/$appId'
import { Route as ApisProductIdRouteImport } from './routes/apis/$productId'
import { Route as AdminTeamsRouteImport } from './routes/admin/teams'
import { Route as AdminSubscriptionsRouteImport } from './routes/admin/subscriptions'
import { Route as AdminAppsRouteImport } from './routes/admin/apps'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsIndexRoute = TeamsIndexRouteImport.update({
  id: '/teams/',
  path: '/teams/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsIndexRoute = AppsIndexRouteImport.update({
  id: '/apps/',
  path: '/apps/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApisIndexRoute = ApisIndexRouteImport.update({
  id: '/apis/',
  path: '/apis/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsTeamIdRoute = TeamsTeamIdRouteImport.update({
  id: '/teams/$teamId',
  path: '/teams/$teamId',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsAppIdRoute = AppsAppIdRouteImport.update({
  id: '/apps/$appId',
  path: '/apps/$appId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApisProductIdRoute = ApisProductIdRouteImport.update({
  id: '/apis/$productId',
  path: '/apis/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTeamsRoute = AdminTeamsRouteImport.update({
  id: '/admin/teams',
  path: '/admin/teams',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSubscriptionsRoute = AdminSubscriptionsRouteImport.update({
  id: '/admin/subscriptions',
  path: '/admin/subscriptions',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAppsRoute = AdminAppsRouteImport.update({
  id: '/admin/apps',
  path: '/admin/apps',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin/apps': typeof AdminAppsRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/teams': typeof AdminTeamsRoute
  '/apis/$productId': typeof ApisProductIdRoute
  '/apps/$appId': typeof AppsAppIdRoute
  '/teams/$teamId': typeof TeamsTeamIdRoute
  '/apis/': typeof ApisIndexRoute
  '/apps/': typeof AppsIndexRoute
  '/teams/': typeof TeamsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/apps': typeof AdminAppsRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/teams': typeof AdminTeamsRoute
  '/apis/$productId': typeof ApisProductIdRoute
  '/apps/$appId': typeof AppsAppIdRoute
  '/teams/$teamId': typeof TeamsTeamIdRoute
  '/apis': typeof ApisIndexRoute
  '/apps': typeof AppsIndexRoute
  '/teams': typeof TeamsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin/apps': typeof AdminAppsRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/teams': typeof AdminTeamsRoute
  '/apis/$productId': typeof ApisProductIdRoute
  '/apps/$appId': typeof AppsAppIdRoute
  '/teams/$teamId': typeof TeamsTeamIdRoute
  '/apis/': typeof ApisIndexRoute
  '/apps/': typeof AppsIndexRoute
  '/teams/': typeof TeamsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin/apps'
    | '/admin/subscriptions'
    | '/admin/teams'
    | '/apis/$productId'
    | '/apps/$appId'
    | '/teams/$teamId'
    | '/apis/'
    | '/apps/'
    | '/teams/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/apps'
    | '/admin/subscriptions'
    | '/admin/teams'
    | '/apis/$productId'
    | '/apps/$appId'
    | '/teams/$teamId'
    | '/apis'
    | '/apps'
    | '/teams'
  id:
    | '__root__'
    | '/'
    | '/admin/apps'
    | '/admin/subscriptions'
    | '/admin/teams'
    | '/apis/$productId'
    | '/apps/$appId'
    | '/teams/$teamId'
    | '/apis/'
    | '/apps/'
    | '/teams/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminAppsRoute: typeof AdminAppsRoute
  AdminSubscriptionsRoute: typeof AdminSubscriptionsRoute
  AdminTeamsRoute: typeof AdminTeamsRoute
  ApisProductIdRoute: typeof ApisProductIdRoute
  AppsAppIdRoute: typeof AppsAppIdRoute
  TeamsTeamIdRoute: typeof TeamsTeamIdRoute
  ApisIndexRoute: typeof ApisIndexRoute
  AppsIndexRoute: typeof AppsIndexRoute
  TeamsIndexRoute: typeof TeamsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams/': {
      id: '/teams/'
      path: '/teams'
      fullPath: '/teams/'
      preLoaderRoute: typeof TeamsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps/': {
      id: '/apps/'
      path: '/apps'
      fullPath: '/apps/'
      preLoaderRoute: typeof AppsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apis/': {
      id: '/apis/'
      path: '/apis'
      fullPath: '/apis/'
      preLoaderRoute: typeof ApisIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams/$teamId': {
      id: '/teams/$teamId'
      path: '/teams/$teamId'
      fullPath: '/teams/$teamId'
      preLoaderRoute: typeof TeamsTeamIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps/$appId': {
      id: '/apps/$appId'
      path: '/apps/$appId'
      fullPath: '/apps/$appId'
      preLoaderRoute: typeof AppsAppIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apis/$productId': {
      id: '/apis/$productId'
      path: '/apis/$productId'
      fullPath: '/apis/$productId'
      preLoaderRoute: typeof ApisProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/teams': {
      id: '/admin/teams'
      path: '/admin/teams'
      fullPath: '/admin/teams'
      preLoaderRoute: typeof AdminTeamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/subscriptions': {
      id: '/admin/subscriptions'
      path: '/admin/subscriptions'
      fullPath: '/admin/subscriptions'
      preLoaderRoute: typeof AdminSubscriptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/apps': {
      id: '/admin/apps'
      path: '/admin/apps'
      fullPath: '/admin/apps'
      preLoaderRoute: typeof AdminAppsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminAppsRoute: AdminAppsRoute,
  AdminSubscriptionsRoute: AdminSubscriptionsRoute,
  AdminTeamsRoute: AdminTeamsRoute,
  ApisProductIdRoute: ApisProductIdRoute,
  AppsAppIdRoute: AppsAppIdRoute,
  TeamsTeamIdRoute: TeamsTeamIdRoute,
  ApisIndexRoute: ApisIndexRoute,
  AppsIndexRoute: AppsIndexRoute,
  TeamsIndexRoute: TeamsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
